###
# Configuration file
# Contains site data, core jekyll config, plugin config, etc.

## Org settings
title: Wem gehört Hamburg

## Site Description
# used in meta tags
description: >
  Mieten gehen durch die Decke. Für viele wird das Wohnen in der Stadt zur Existenzfrage.
  Kann ich mir ein Leben in meiner Stadt noch leisten, fragen sich Mieter in Hamburg.
  Vielleicht auch Sie?


## Core Site Settings
# jekyll configuration
baseurl: ''
permalink: none
assets-base-url: '/assets/'
source: src
destination: dist
site-theme: default
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: ['dev']
# modules
include: ['_pages', '_posts', '_data']
exclude: ['js', 'sass', 'node_modules', Gemfile, Gemfile.lock, notes.txt, package.json, README.md, 'bower.json']
keep_files:
  - assets
markdown: kramdown
gems:
  - jekyll-seo-tag

# SEO Specific Settings
twitter:
  username: correctiv_org
  domain: correctiv.org
facebook:
  app_id:
