###
# Configuration file
# Contains site data, core jekyll config, plugin config, etc.

## Org settings
title: Wem gehört Hamburg?

## Site Description
# used in meta tags
description: >
  Hamburg ist für Investoren eine der lukrativsten Städte in Europa. Doch die Eigentümer sind verborgen. Gemeinsam können wir das ändern.

## Core Site Settings
# jekyll configuration
baseurl: ''
permalink: none
source: .
destination: dist
site-theme: default
image: assets/images/wghh-teaser.jpg
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: ['dev']
# modules
include: ['_pages', '_posts', '_data']
exclude: ['assets/js', 'assets/sass', 'assets/fonts', 'node_modules', Gemfile, Gemfile.lock, notes.txt, package.json, README.md, 'bower.json']
keep_files:
  - assets
markdown: kramdown
gems:
  - jekyll-seo-tag

# SEO Specific Settings
url: https://wem-gehoert-hamburg.de
twitter:
  username: correctiv_org
  domain: correctiv.org
facebook:
  app_id:
